### ISSUE TITLE
"placeholder_replacements" not work

### ISSUE THREAD

**Issue by Ceale** [WiIIiam278/Velocitab#243]
`tab_groups.yml`:
``` yaml
format: <white><color:#a6d714><b>〔%server%〕</b></color:#a6d714>%username%  </white>

# ------------------------------------

placeholder_replacements:
  '%server%':
  - placeholder: lobby
    replacement: "大厅"
  - placeholder: revres
    replacement: "器务服"
```
When `%server%` is `revres`, it should be replaced with `器务服`; and when `%server%` is `lobby`, it should be replaced with `大厅`. However, in reality, no replacement occurs, and `%server%` is displayed as it is (i.e., `lobby` or `revres`).
This English text was translated using AI, and I am unsure if it contains any errors.

---

当`%server%`为`revres`时，其应该被替换为`器务服`；而当`%server%`为`lobby`时，则应该替换为`大厅`。但是事实上没有替换，`%server%`被按照原样显示了（即`lobby` or `revres`）
