### ISSUE TITLE
Failed Dispatch Packet on server disconnect

### ISSUE THREAD

**Issue by Anthony-Mariotti** [WiIIiam278/Velocitab#26]
I'm still debugging, but I'm trying to determine the cause of this error when a player disconnects from it. It logs, depending on the scenario, 2-10 of the same error message that I posted below.

Environment: `itzg/docker-bungeecord`
Velocity: `Velocity 3.2.0-SNAPSHOT (git-36cc2bde-b245)`
Minecraft: `1.19.4`
Plugins:
- `luckperms 5.4.67 by Luck`
- `protocolize v2 by Exceptionflug`
- `velocitab 1.2.3 by William278`
- `venturechat 3.5.0 by Aust1n46`

<details>
<summary>Error Snippet</summary>

```
traxmc-prison-1    | [03:04:20 INFO]: AMTraxTGE joined the game
traxmc-prison-1    | [03:04:20 INFO]: AMTraxTGE[/1xx.xxx.xxx.xxx:xxxxx] logged in with entity id 39 at ([world]0.5, 65.0, 0.5)
traxmc-lobby-1     | [03:04:20 INFO]: AMTraxTGE lost connection: Disconnected
traxmc-lobby-1     | [03:04:20 INFO]: - AMTraxTGE Disconnected
[07:04:22 INFO]: [connected player] AMTraxTGE (/1xx.xxx.xxx.xxx:xxxxx) has disconnected
[07:04:22 ERROR] [velocitab]: Failed to dispatch packet (is the client or server modded or using an illegal version?)
traxmc-proxy-1     | java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.api.player.ProtocolizePlayer.sendPacket(Object)" because the return value of "dev.simplix.protocolize.api.providers.ProtocolizePlayerProvider.player(java.util.UUID)" is null
traxmc-proxy-1     |    at net.william278.velocitab.packet.ScoreboardManager.dispatchPacket(ScoreboardManager.java:57) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.packet.ScoreboardManager.lambda$updateRoles$4(ScoreboardManager.java:49) ~[?:?]
traxmc-proxy-1     |    at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.packet.ScoreboardManager.updateRoles(ScoreboardManager.java:49) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePlayer$17(PlayerTabList.java:156) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePlayer$18(PlayerTabList.java:152) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.updatePlayer(PlayerTabList.java:152) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePeriodically$21(PlayerTabList.java:183) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePeriodically$22(PlayerTabList.java:182) ~[?:?]
traxmc-proxy-1     |    at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:242) ~[velocity-3.2.0-SNAPSHOT-245.jar:3.2.0-SNAPSHOT (git-36cc2bde-b245)]
traxmc-proxy-1     |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
traxmc-proxy-1     |    at java.lang.Thread.run(Thread.java:833) [?:?]
[07:04:22 INFO]: [server connection] AMTraxTGE -> prison has disconnected
[07:04:22 ERROR] [velocitab]: Failed to dispatch packet (is the client or server modded or using an illegal version?)
traxmc-proxy-1     | java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.api.player.ProtocolizePlayer.sendPacket(Object)" because the return value of "dev.simplix.protocolize.api.providers.ProtocolizePlayerProvider.player(java.util.UUID)" is null
traxmc-proxy-1     |    at net.william278.velocitab.packet.ScoreboardManager.dispatchPacket(ScoreboardManager.java:57) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.packet.ScoreboardManager.updateRoles(ScoreboardManager.java:50) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePlayer$17(PlayerTabList.java:156) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePlayer$18(PlayerTabList.java:152) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.updatePlayer(PlayerTabList.java:152) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePeriodically$21(PlayerTabList.java:183) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePeriodically$22(PlayerTabList.java:182) ~[?:?]
traxmc-proxy-1     |    at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:242) ~[velocity-3.2.0-SNAPSHOT-245.jar:3.2.0-SNAPSHOT (git-36cc2bde-b245)]
traxmc-proxy-1     |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
traxmc-proxy-1     |    at java.lang.Thread.run(Thread.java:833) [?:?]
traxmc-prison-1    | [03:04:22 INFO]: AMTraxTGE lost connection: Disconnected
traxmc-prison-1    | [03:04:22 INFO]: AMTraxTGE left the game
```
</details>

<details>
<summary>Config</summary>

```yml
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃       Velocitab Config       ┃
# ┃    Developed by William278   ┃
# ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# ┗╸ Placeholders: %players_online%, %max_players_online%, %local_players_online%, %current_date%, %current_time%, %username%, %server%, %ping%, %prefix%, %suffix%, %role%
headers:
    default: "&aWelcome to &6TraxMC&a"
    prison: "&aWelcome to &dPrison&a on &6TraxMC&a!"
footers:
    default: "Players: %players_online%/%max_players_online%"
    prison: "Inmates: %local_players_online%"
formats:
    default: "&f%prefix%&f %username% &6%ping%&ams "
    prison: "&f%prefix%&f %username% &6%ping%&ams "
# Which text formatter to use (MINEDOWN or MINIMESSAGE)
formatting_type: MINEDOWN
# The servers in each group of servers
server_groups:
    default:
        - lobby
    prison:
        - prison
# All servers which are not in other groups will be put in the fallback group.
# "false" will exclude them from Velocitab.
fallback_enabled: true
# The formats to use for the fallback group.
fallback_group: default
enable_papi_hook: true
# If you are using MINIMESSAGE formatting, enable this to support MiniPlaceholders in formatting.
enable_miniplaceholders_hook: true
# Ordered list of elements by which players should be sorted. (ROLE_WEIGHT, ROLE_NAME and SERVER are supported)
sort_players_by:
    - ROLE_WEIGHT
    - ROLE_NAME
# How often to periodically update the TAB list, including header and footer, for all users.
# Will only update on player join/leave if set to 0.
update_rate: 10
```
</details>

I'm still configuring this server, so if there is a solution that happens to be a compatibility issue, I will update this

**Comment by WiIIiam278** [comment]
If it can't find the player by uuid is your user forwarding setup correctly and offline mode on the proxy disabled?

**Comment by Anthony-Mariotti** [comment]
For offline mode disabled, meaning that the proxy is "online" and authenticates with Mojang? Here is just the configuration for the proxy. Would it be possible it is attempting to update the tablist when the player has already left and can't find the user/uuid?

<details>
<summary>velocity.toml</summary>

```toml
# Config version. Do not change this
config-version = "2.6"

# What port should the proxy be bound to? By default, we'll bind to all addresses on port 25577.
bind = "0.0.0.0:25577"

# What should be the MOTD? This gets displayed when the player adds your server to
# their server list. Only MiniMessage format is accepted.
motd = "<#09add3>Developing TraxMC"

# What should we display for the maximum number of players? (Velocity does not support a cap
# on the number of players online.)
show-max-players = 500

# Should we authenticate players with Mojang? By default, this is on.
online-mode = true

# Should the proxy enforce the new public key security standard? By default, this is on.
force-key-authentication = true

# If client's ISP/AS sent from this proxy is different from the one from Mojang's
# authentication server, the player is kicked. This disallows some VPN and proxy
# connections but is a weak form of protection.
prevent-client-proxy-connections = false

# Should we forward IP addresses and other data to backend servers?
# Available options:
# - "none":        No forwarding will be done. All players will appear to be connecting
#                  from the proxy and will have offline-mode UUIDs.
# - "legacy":      Forward player IPs and UUIDs in a BungeeCord-compatible format. Use this
#                  if you run servers using Minecraft 1.12 or lower.
# - "bungeeguard": Forward player IPs and UUIDs in a format supported by the BungeeGuard
#                  plugin. Use this if you run servers using Minecraft 1.12 or lower, and are
#                  unable to implement network level firewalling (on a shared host).
# - "modern":      Forward player IPs and UUIDs as part of the login process using
#                  Velocity's native forwarding. Only applicable for Minecraft 1.13 or higher.
player-info-forwarding-mode = "MODERN"

# If you are using modern or BungeeGuard IP forwarding, configure a file that contains a unique secret here.
# The file is expected to be UTF-8 encoded and not empty.
forwarding-secret-file = "forwarding.secret"

# Announce whether or not your server supports Forge. If you run a modded server, we
# suggest turning this on.
# 
# If your network runs one modpack consistently, consider using ping-passthrough = "mods"
# instead for a nicer display in the server list.
announce-forge = false

# If enabled (default is false) and the proxy is in online mode, Velocity will kick
# any existing player who is online if a duplicate connection attempt is made.
kick-existing-players = false

# Should Velocity pass server list ping requests to a backend server?
# Available options:
# - "disabled":    No pass-through will be done. The velocity.toml and server-icon.png
#                  will determine the initial server list ping response.
# - "mods":        Passes only the mod list from your backend server into the response.
#                  The first server in your try list (or forced host) with a mod list will be
#                  used. If no backend servers can be contacted, Velocity won't display any
#                  mod information.
# - "description": Uses the description and mod list from the backend server. The first
#                  server in the try (or forced host) list that responds is used for the
#                  description and mod list.
# - "all":         Uses the backend server's response as the proxy response. The Velocity
#                  configuration is used if no servers could be contacted.
ping-passthrough = "DISABLED"

# If not enabled (default is true) player IP addresses will be replaced by <ip address withheld> in logs
enable-player-address-logging = true

[servers]
# Configure your servers here. Each key represents the server's name, and the value
# represents the IP address of the server to connect to.
lobby = "lobby:25565"
prison = "prison:25565"

# In what order we should try servers when a player logs in or is kicked from a server.
try = [
    "lobby"
]

[forced-hosts]
# Configure your forced hosts here.
"<withheld>" = [
    "lobby"
]

[advanced]
# How large a Minecraft packet has to be before we compress it. Setting this to zero will
# compress all packets, and setting it to -1 will disable compression entirely.
compression-threshold = 256

# How much compression should be done (from 0-9). The default is -1, which uses the
# default level of 6.
compression-level = -1

# How fast (in milliseconds) are clients allowed to connect after the last connection? By
# default, this is three seconds. Disable this by setting this to 0.
login-ratelimit = 3000

# Specify a custom timeout for connection timeouts here. The default is five seconds.
connection-timeout = 5000

# Specify a read timeout for connections here. The default is 30 seconds.
read-timeout = 30000

# Enables compatibility with HAProxy's PROXY protocol. If you don't know what this is for, then
# don't enable it.
haproxy-protocol = false

# Enables TCP fast open support on the proxy. Requires the proxy to run on Linux.
tcp-fast-open = false

# Enables BungeeCord plugin messaging channel support on Velocity.
bungee-plugin-message-channel = true

# Shows ping requests to the proxy from clients.
show-ping-requests = false

# By default, Velocity will attempt to gracefully handle situations where the user unexpectedly
# loses connection to the server without an explicit disconnect message by attempting to fall the
# user back, except in the case of read timeouts. BungeeCord will disconnect the user instead. You
# can disable this setting to use the BungeeCord behavior.
failover-on-unexpected-server-disconnect = true

# Declares the proxy commands to 1.13+ clients.
announce-proxy-commands = true

# Enables the logging of commands
log-command-executions = false

# Enables logging of player connections when connecting to the proxy, switching servers
# and disconnecting from the proxy.
log-player-connections = true

[query]
# Whether to enable responding to GameSpy 4 query responses or not.
enabled = false

# If query is enabled, on what port should the query protocol listen on?
port = 25577

# This is the map name that is reported to the query services.
map = "Velocity"

# Whether plugins should be shown in query response by default or not
show-plugins = false
```
</details>
