### ISSUE TITLE
Latest Velocity snapshot breaks tablist functionality

### ISSUE THREAD

**Issue by RHX0R3** [WiIIiam278/Velocitab#260]

**Comment by RHX0R3** [comment]
Everything loads normally. No errors occur.

I downgraded to the regular release 1.7.5 and it works again.

**Comment by nhanledev** [comment]
tab_group default setting has error with the new version

```
  placeholder_replacements:
    '%current_date_weekday_en-US%':
    - placeholder: Monday
      replacement: <red>Monday</red>
    - placeholder: Tuesday
      replacement: <gold>Tuesday</gold>
    - placeholder: Else
      replacement: <green>Other day</green>
```

replace to

```
placeholder_replacements: {}
```
