### ISSUE TITLE
Placeholder not resolved when joining with a second Minecraft instance

### ISSUE THREAD

**Issue by fof1092** [WiIIiam278/Velocitab#264]
**Description**:
The placeholder from my `tab_groups.yml` is not being resolved when joining the server with a second Minecraft instance using the same account. This issue is reproducible and persists at least up to commit `6ff785fb14feb6245dfaa69ccdfc4d27deadc375`. After this commit, I encountered the issue described in #263, but I suspect the problem may still exist in the latest version.

And last but not least, thank you very much for this great plugin! :)

**Steps to Reproduce**:
1. Open two Minecraft instances.
2. Join the server with the first instance.
3. Join the server with the second instance using the same account.

**Expected Behavior**:
The placeholder should be resolved correctly for the second instance upon joining.

**Actual Behavior**:
The placeholder is not resolved when the second instance joins.

As a note, in version 1.7.3 we created a placeholder with the same name to solve similar problems, but this is no longer possible, the option was very useful though!
(see our `tab_groups.yml` => - Placeholder: `%luckperms_last_group_on_tracks_global_level%`):

![Image](https://github.com/user-attachments/assets/89861ce6-1cb8-45bf-9890-7850fd3414fc)

**Log Details**:
It appears from the Velocity log that a player joins and then gets kicked, which may be related to this issue (this is just a suspicion).
```
[10:01:12 INFO]: [connected player] F_o_F_1092 (/XXX.XXX.XXX.XXX:XXXXX) has connected
[10:01:12 INFO]: [connected player] F_o_F_1092 (/XXX.XXX.XXX.XXX:XXXXX) has disconnected: 
[10:01:12 INFO]: [server connection] F_o_F_1092 -> Freimaurer has disconnected
[10:01:12 INFO]: [server connection] F_o_F_1092 -> Freimaurer has connected
```

**Environment**:
- Plugin Name: Velocitab
- Plugin Version: From commit `6ff785fb14feb6245dfaa69ccdfc4d27deadc375`
- Server Version: 3.4.0-SNAPSHOT #498 (latest)
- Configuration Files: 

config.yml

```
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃       Velocitab Config       ┃
# ┃  by William278 & AlexDev03   ┃
# ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# ┣╸ Information: https://william278.net/project/velocitab
# ┗╸ Documentation: https://william278.net/docs/velocitab

# Check for updates on startup
check_for_updates: false
# Whether to remove nametag from players' heads if the nametag associated with their server group is empty.
remove_nametags: true
# Whether to disable header and footer if they are empty and let backend servers handle them.
disable_header_footer_if_empty: true
# Which text formatter to use (MINIMESSAGE, MINEDOWN or LEGACY)
formatter: MINEDOWN
# All servers which are not in other groups will be put in the fallback group.
# "false" will exclude them from Velocitab.
fallback_enabled: true
# The formats to use for the fallback group.
fallback_group: default
# Whether to show all players from all groups in the TAB list.
show_all_players_from_all_groups: false
# Whether to enable the PAPIProxyBridge hook for PAPI support
enable_papi_hook: true
# How long in seconds to cache PAPI placeholders for, in milliseconds. (0 to disable)
papi_cache_time: 30000
# If you are using MINIMESSAGE formatting, enable this to support MiniPlaceholders in formatting.
enable_mini_placeholders_hook: true
# Whether to send scoreboard teams packets. Required for player list sorting and nametag formatting.
# Turn this off if you're using scoreboard teams on backend servers.
send_scoreboard_packets: false
# If built-in placeholders return a blank string, fallback to Placeholder API equivalents.
# For example, if %prefix% returns a blank string, use %luckperms_prefix%. Requires PAPIProxyBridge.
fallback_to_papi_if_placeholder_blank: true
# Whether to sort players in the TAB list.
sort_players: true
# Remove gamemode spectator effect for other players in the TAB list.
remove_spectator_effect: true
# Whether to enable the Plugin Message API (allows backend plugins to perform certain operations)
enable_plugin_message_api: true
# Whether to force sending tab list packets to all players, even if a packet for that action has already been sent. This could fix issues with some mods.
force_sending_tab_list_packets: false
# Whether to enable relational placeholders. With an high amount of players, this could cause lag.
enable_relational_placeholders: false
# A list of links that will be sent to display on player pause menus (Minecraft 1.21+ clients only).
# • Labels can be fully custom or built-in (one of 'bug_report', 'community_guidelines', 'support', 'status',
#   'feedback', 'community', 'website', 'forums', 'news', or 'announcements').
# • If you supply a url with a 'bug_report' label, it will be shown if the player is disconnected.
# • Specify a set of server groups each URL should be sent on. Use '*' to show a URL to all groups.
server_links:
- label: '&6&l🌟 Neuigkeiten & Updates'
  url: https://www.minecraft-spielplatz.net
  groups:
  - '*'
- label: '&a&l📚 Minecraft-Spielplatz Wiki'
  url: https://wiki.minecraft-spielplatz.net
  groups:
  - '*'
- label: '&e&l📝 Regeln & Verhaltenskodex'
  url: https://wiki.minecraft-spielplatz.net/regeln
  groups:
  - '*'
- label: '&e&l💻 Befehlsübersicht'
  url: https://wiki.minecraft-spielplatz.net/befehle
  groups:
  - '*'
- label: '&e&l🏆 Ränge & Level'
  url: https://wiki.minecraft-spielplatz.net/ränge-und-level/
  groups:
  - '*'
- label: '&b&l❓ Hilfe & Support'
  url: https://wiki.minecraft-spielplatz.net/hilfe-und-support
  groups:
  - '*'
- label: '&c&l💬 Forum & Diskussionen'
  url: https://www.minecraft-spielplatz.net
  groups:
  - '*'
- label: '&d&l🎮 Trete unserem Discord bei!'
  url: https://discord.gg/cFjYuPgUYs
  groups:
  - '*'
```

tab_groups.yml
```
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃     Velocitab Tab Groups     ┃
# ┃  by William278 & AlexDev03   ┃
# ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# ┣╸ Information: https://william278.net/project/velocitab
# ┗╸ Documentation: https://william278.net/docs/velocitab

groups:
- name: default
  headers:
  - \n&2&l◀ &r &r &a&l◀ &r &2&l◀ &a&lMi&2&lne&a&lcr&2&laft&a&l-&2&lSp&a&lie&2&llp&a&lla&2&ltz&r
    &2&l▶ &r &a&l▶ &r &r &2&l▶\n
  footers:
  - \n&9&l[&b&l&oInfo&9&l]\n &6Support-Tickets &7kannst du im\n &6Forum & Discord
    &7unter &6Support-Tickets &7erstellen.\n
  format: ' %suffix%[&b&o%luckperms_last_group_on_tracks_global_level%%suffix%] %suffix%&l%prefix%
    &f&l⋙ %suffix%%username% &f&l⋙ &f&o%server%'
  nametag:
    prefix: '%suffix%[&b&o%luckperms_last_group_on_tracks_global_level%%suffix%] '
    suffix: ''
  servers:
  - Events
  - Mine
  - CityBuild
  - Creators
  - ServerTeam
  - Wettbewerb
  - HelferInnenTeam
  - Freimaurer
  sorting_placeholders:
  - '%role_weight%'
  - '%username_lower%'
  placeholder_replacements:
    '%luckperms_last_group_on_tracks_global_level%':
    - placeholder: '%luckperms_last_group_on_tracks_global_level%'
      replacement: '&c&o⚠'
    - placeholder: ''
      replacement: '0'
    - placeholder: global_level_0
      replacement: '0'
    - placeholder: global_level_1
      replacement: '1'
    - placeholder: global_level_2
      replacement: '2'
    - placeholder: global_level_3
      replacement: '3'
    - placeholder: global_level_4
      replacement: '4'
    - placeholder: global_level_5
      replacement: '5'
    - placeholder: global_level_6
      replacement: '6'
    - placeholder: global_level_7
      replacement: '7'
    - placeholder: global_level_8
      replacement: '8'
    - placeholder: global_level_9
      replacement: '9'
    - placeholder: global_level_10
      replacement: '10'
    - placeholder: global_level_11
      replacement: '11'
    - placeholder: global_level_12
      replacement: '12'
    - placeholder: global_level_13
      replacement: '13'
    - placeholder: global_level_14
      replacement: '14'
    - placeholder: global_level_15
      replacement: '15'
    - placeholder: global_level_16
      replacement: '16'
    - placeholder: global_level_17
      replacement: '17'
    - placeholder: global_level_18
      replacement: '18'
    - placeholder: global_level_19
      replacement: '19'
    - placeholder: global_level_20
      replacement: '20'
    - placeholder: global_level_21
      replacement: '21'
    - placeholder: global_level_22
      replacement: '22'
    - placeholder: global_level_23
      replacement: '23'
    - placeholder: global_level_24
      replacement: '24'
    - placeholder: global_level_25
      replacement: '25'
    - placeholder: global_level_26
      replacement: '26'
    - placeholder: global_level_27
      replacement: '27'
    - placeholder: global_level_28
      replacement: '28'
    - placeholder: global_level_29
      replacement: '29'
    - placeholder: global_level_30
      replacement: '30'
    - placeholder: global_level_31
      replacement: '31'
    - placeholder: global_level_32
      replacement: '32'
    - placeholder: global_level_33
      replacement: '33'
    - placeholder: global_level_34
      replacement: '34'
    - placeholder: global_level_35
      replacement: '35'
    - placeholder: global_level_36
      replacement: '36'
    - placeholder: global_level_37
      replacement: '37'
    - placeholder: global_level_38
      replacement: '38'
    - placeholder: global_level_39
      replacement: '39'
    - placeholder: global_level_40
      replacement: '40'
    - placeholder: global_level_41
      replacement: '41'
    - placeholder: global_level_42
      replacement: '42'
    - placeholder: global_level_43
      replacement: '43'
    - placeholder: global_level_44
      replacement: '44'
    - placeholder: global_level_45
      replacement: '45'
    - placeholder: global_level_46
      replacement: '46'
    - placeholder: global_level_47
      replacement: '47'
    - placeholder: global_level_48
      replacement: '48'
    - placeholder: global_level_49
      replacement: '49'
    - placeholder: global_level_50
      replacement: '50'
  collisions: false
  header_footer_update_rate: 1000
  format_update_rate: 1000
  nametag_update_rate: 1000
  placeholder_update_rate: 1000
  only_list_players_in_same_server: false
```
