### ISSUE TITLE
Server name placeholder not applying mapped display names

### ISSUE THREAD

**Issue by FreeMonoid** [WiIIiam278/Velocitab#27]
I would like to be able to use shorter server names in the TAB list since they sometimes take too much space.

This was mentioned in #14, but I think there was a bit of miscommunication about what exactly is the desired behavior 🙂 

---

As far as implementation is concerned, I was thinking of adding a new config section:

```yaml
# Define custom names to be shown in the TAB list for specific server names.
# If no custom display name is provided for a server, its original name will be used.
server_display_names:
  very-long-server-name: 'VLSN'
```

Then when replacing `%server%` placeholder (via `TabPlayer.getServerName`), we would look at the mapping in the config and use display name if needed.
