### ISSUE TITLE
[ALPHA] Exception Index out of bounds of array

### ISSUE THREAD

**Issue by Anthony-Mariotti** [WiIIiam278/Velocitab#29]
Further development into my server and I found that I started receiving an `IndexOutOfBoundsException` while joining and just interacting with my server. It would throw approximately every few minutes, but it gets thrown on the first restart of the server, and the first player join since I restart them a lot while developing. 

So to reproduce this on startup, I had to restart all three servers (proxy, lobby, prison) and join the server. From what I've seen, you must be connected when the server shutdown happens, but only sometimes.

Additionally, it still tries and iterates regardless of list size, so it will throw the error ten times if the number passed is ten. It also seems when I disable `update_rate` to `0`, the issue does not occur, but it does still happen randomly within the `update_rate` window when it is set, regardless of the first join; it just takes some time, and I'll have a console full of the exception.

Environment: `itzg/docker-bungeecord`
Velocity: `Velocity 3.2.0-SNAPSHOT (git-93b6376b-b246)`
Minecraft: `1.19.4`
Velocitab: `ALPHA v1.2.3` - f14a92b

Plugins:
- `luckperms 5.4.67 by Luck`
- `protocolize v2 by Exceptionflug`
- `venturechat 3.5.0 by Aust1n46`

<details>
<summary>Error Snippet 01</summary>

```
[04:23:19 ERROR]: Exception in task net.william278.velocitab.tab.PlayerTabList$$Lambda$1052/0x00000008012be630@4a1eadb9 by plugin Velocitab
traxmc-proxy-1     | java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
traxmc-proxy-1     |    at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
traxmc-proxy-1     |    at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
traxmc-proxy-1     |    at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
traxmc-proxy-1     |    at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
traxmc-proxy-1     |    at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.config.Settings.getHeader(Settings.java:90) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.getHeader(PlayerTabList.java:173) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.player.TabPlayer.sendHeaderAndFooter(TabPlayer.java:60) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePeriodically$21(PlayerTabList.java:202) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePeriodically$22(PlayerTabList.java:200) ~[?:?]
traxmc-proxy-1     |    at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:242) ~[velocity-3.2.0-SNAPSHOT-246.jar:3.2.0-SNAPSHOT (git-93b6376b-b246)]
traxmc-proxy-1     |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
traxmc-proxy-1     |    at java.lang.Thread.run(Thread.java:833) [?:?]
```
</details>

<details>
<summary>Error Snippet 02</summary>

```
[04:26:23 ERROR]: Exception in task net.william278.velocitab.tab.PlayerTabList$$Lambda$1052/0x00000008012c0738@53b1d4f7 by plugin Velocitab
traxmc-proxy-1     | java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 1
traxmc-proxy-1     |    at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
traxmc-proxy-1     |    at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
traxmc-proxy-1     |    at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
traxmc-proxy-1     |    at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
traxmc-proxy-1     |    at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.config.Settings.getHeader(Settings.java:90) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.getHeader(PlayerTabList.java:173) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.player.TabPlayer.sendHeaderAndFooter(TabPlayer.java:60) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePeriodically$21(PlayerTabList.java:202) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
traxmc-proxy-1     |    at net.william278.velocitab.tab.PlayerTabList.lambda$updatePeriodically$22(PlayerTabList.java:200) ~[?:?]
traxmc-proxy-1     |    at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:242) ~[velocity-3.2.0-SNAPSHOT-246.jar:3.2.0-SNAPSHOT (git-93b6376b-b246)]
traxmc-proxy-1     |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
traxmc-proxy-1     |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
traxmc-proxy-1     |    at java.lang.Thread.run(Thread.java:833) [?:?]
```
</details>

<details>
<summary>Config</summary>

```
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃       Velocitab Config       ┃
# ┃    Developed by William278   ┃
# ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# ┗╸ Placeholders: %players_online%, %max_players_online%, %local_players_online%, %current_date%, %current_time%, %username%, %server%, %ping%, %prefix%, %suffix%, %role%
headers:
    default:
        - "&aWelcome to &6TraxMC&a"
    prison:
        - "&aWelcome to &dPrison&a on &6TraxMC&a!"
footers:
    default:
        - "Players: %players_online%/%max_players_online%"
    prison:
        - "Inmates: %local_players_online%"
formats:
    default: "&f%prefix%&f %username% &6%ping%&ams "
    prison: "&f%prefix%&f %username% &6%ping%&ams "
# Which text formatter to use (MINEDOWN or MINIMESSAGE)
formatting_type: MINEDOWN
# The servers in each group of servers
server_groups:
    default:
        - lobby
    prison:
        - prison
# All servers which are not in other groups will be put in the fallback group.
# "false" will exclude them from Velocitab.
fallback_enabled: true
# The formats to use for the fallback group.
fallback_group: default
enable_papi_hook: true
# If you are using MINIMESSAGE formatting, enable this to support MiniPlaceholders in formatting.
enable_miniplaceholders_hook: true
# Ordered list of elements by which players should be sorted. (ROLE_WEIGHT, ROLE_NAME and SERVER are supported)
sort_players_by:
    - ROLE_WEIGHT
    - ROLE_NAME
# How often to periodically update the TAB list, including header and footer, for all users.
# Will only update on player join/leave if set to 0.
update_rate: 10

```
</details>

I have additional backend server plugins that could interfere with this, but I have tried disabling and re-enabling them constantly. Unfortunately, I couldn't find a happy medium between it working or not working.

Backend Server Plugins:
- `SuperLobby v4.5.7`
- `VentureChat v3.5.0`
- etc

I called out these two plugins because they have some possible manipulation of the tab list or chat. `VentureChat` is for network chatting cross-server, installed on all backends plus the proxy. Whereas `SuperLobby` is installed on all backends for their initial lobbies and has a tab hook, I have disabled it.

p.s. sorry, I write long stuff... ♥
