### ISSUE TITLE
Allow placing animation sets in a different file

### ISSUE THREAD

**Issue by ultard** [WiIIiam278/Velocitab#58]
Make it possible to place all the animations in a separate file and that each animation worked separately, the sections in the headers and footers used for the lines (not for animation). Because prescribe everything at once in one place it is unrealistically difficult to do and think through all the animations ahead of a huge text.

config.yml
```yml
headers:
  default:
    - "%animation:Welcome%"

footers:
  default:
    - "%animation:MyAnimation1%"
```

animations.yml
```yml
Welcome:
  change-interval: 400
  texts:
  - '&7&lW_'
  - '&7&lW_'
  - '&7&lWe_'
  - '&7&lWel_'
  - '&7&lWelc_'
  - '&7&lWelco_'
  - '&7&lWelcom_'
  - '&7&lWelcome_'
  - '&7&lWelcome_'
  - '&7&lWelcome_'
  - '&7&lWelcome_'
  - '&7&lWelcom_'
  - '&7&lWelco_'
  - '&7&lWelc_'
  - '&7&lWel_'
  - '&7&lWe_'
  - '&7&lW_'
  - '&7&lW_'
MyAnimation1:
  change-interval: 100
  texts:
    - '&d-&3--------------'
    - '&3-&d-&3-------------'
    - '&3--&d-&3------------'
    - '&3---&d-&3-----------'
    - '&3----&d-&3----------'
    - '&3-----&d-&3---------'
    - '&3------&d-&3--------'
    - '&3-------&d-&3-------'
    - '&3--------&d-&3------'
    - '&3---------&d-&3-----'
    - '&3----------&d-&3----'
    - '&3-----------&d-&3---'
    - '&3------------&d-&3--'
    - '&3-------------&d-&3-'
    - '&3--------------&d-'
    - '&3-------------&d-&3-'
    - '&3------------&d-&3--'
    - '&3-----------&d-&3---'
    - '&3----------&d-&3----'
    - '&3---------&d-&3-----'
    - '&3--------&d-&3------'
    - '&3-------&d-&3-------'
    - '&3------&d-&3--------'
    - '&3-----&d-&3---------'
    - '&3----&d-&3----------'
    - '&3---&d-&3-----------'
    - '&3--&d-&3------------'
    - '&3-&d-&3-------------'
    - '&d-&3--------------'
```
